#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" app
usermod -o -u "$PUID" app

echo
echo "                       .__         "
echo "    ___  _____ _____  _|__| ____   "
echo "    \  \/  /  |  \  \/ /  |/    \  "
echo "     >    <|  |  /\   /|  |   |  \ "
echo "    /__/\_ \____/  \_/ |__|___|  / "
echo "          \/             ____  \/  "            
echo "                        / ___|     "
echo "                   ___ / /___      "
echo "                  / __|| ___ \     "
echo "                  \__ \| \_/ |     "
echo "                  |___/\_____/     "     
echo 
echo "   ALPINE Base Image with S6-Overlay  "
echo
echo "              GID/UID                "

echo "
      ----------------------
         User UID:    $(id -u app)  
         User GID:    $(id -g app)  
      ----------------------
"
echo "      Setting Directory Owner"
chown -R app:app /app
chown -R app:app /config
echo "               Done."
echo