#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" app
usermod -o -u "$PUID" app

echo
echo '

                       .__        
    ___  _____ _____  _|__| ____  
    \  \/  /  |  \  \/ /  |/    \ 
     >    <|  |  /\   /|  |   |  \
    /__/\_ \____/  \_/ |__|___|  /
          \/             ____  \/              
                        / ___|
                   ___ / /___ 
                  / __|| ___ \
                  \__ \| \_/ |
                  |___/\_____/          

  ALPINE Base Image with S6-Overlay

              GID/UID
'
echo "
      ----------------------
         User UID:    $(id -u app)  
         User GID:    $(id -g app)  
      ----------------------
"
echo "      Setting Directory Owner"
chown -R app:app /app
chown -R app:app /config
echo "               Done."
echo